### ISSUE TITLE
SVG in different colors.

### ISSUE THREAD

**Issue by Subtain-Farooq** [OpenElements/website#11]
![215508380-74a374f1-0d6c-4280-be6f-5ddc317f34fe](https://user-images.githubusercontent.com/42765166/216010074-d0031576-9890-4262-96df-44a7074b64d8.svg)

This SVG must be in blue, as shown in the attached image.

![screenshot-127 0 0 1_1313-2023 02 01-14_06_48](https://user-images.githubusercontent.com/42765166/216010247-0c502544-a3ce-4a7c-8da8-0dcbe69c7133.png)

**Comment by hendrikebbers** [comment]
![img_blue](https://user-images.githubusercontent.com/9443847/218311884-5b7ad8ef-0791-469e-9503-370834717a1e.svg)

**Comment by hendrikebbers** [comment]
@Subtain-Farooq added :)

**Comment by hendrikebbers** [comment]
color variant added in https://github.com/OpenElements/website/issues/7
