### ISSUE TITLE
Design of links in text

### ISSUE THREAD

**Issue by hendrikebbers** [OpenElements/website#18]
For the links in the text we have a new design that need to be implemented.

<img width="940" alt="cta states" src="https://user-images.githubusercontent.com/9443847/220346562-837f8217-6f7b-4aa2-9e56-ef931a85ba91.png">

**Comment by Subtain-Farooq** [comment]
Which one hover effect should be applied? Hover V1 or Hover V2?

**Comment by hendrikebbers** [comment]
V1
