### ISSUE TITLE
Design:Page headers have bad position on high res monitor

### ISSUE THREAD

**Issue by hendrikebbers** [OpenElements/website#33]
On a high resolution monitor the titles of the pages have a bad position. All of them are partly overlapping the blue page header. See attached images for examples.

All pages that need to be checked:
- https://open-elements-de.netlify.app
- https://open-elements-de.netlify.app/about/
- https://open-elements-de.netlify.app/about-hendrik/
- https://open-elements-de.netlify.app/contact/
- https://open-elements-de.netlify.app/privacy-policy/
- https://open-elements-de.netlify.app/impressum/

![Screenshot 2023-04-20 at 10 17 25](https://user-images.githubusercontent.com/9443847/233305469-63485401-9320-4e6a-8179-51033115e713.png)

![Screenshot 2023-04-20 at 10 17 33](https://user-images.githubusercontent.com/9443847/233305523-9641c55a-980b-4296-b713-f296aeff5269.png)

![Screenshot 2023-04-20 at 10 17 40](https://user-images.githubusercontent.com/9443847/233305556-6a010f47-2b0e-429c-b05b-18e6ca74a2fa.png)

![Screenshot 2023-04-20 at 10 18 01](https://user-images.githubusercontent.com/9443847/233305584-530ad2dd-4565-4495-9e47-4f2da6f9d2e7.png)

**Comment by hendrikebbers** [comment]
Currently my idea is to find a way how the background image can stay the same but extended to left and right with a simple background (horizontal color split)

**Comment by Subtain-Farooq** [comment]
Okay I will try find some way to fix this issue.

**Comment by hendrikebbers** [comment]
@Subtain-Farooq I have seen that the behavior is much better now. The designer provided a new header for all pages. Please have a look at the new FIGMA file: https://www.figma.com/file/uNorvr0G3GjpeUruOTOGwk/Open-elements_design?type=design&node-id=0%3A1&t=4tXyvG3BoPg17v4Z-1

[Open elements_design.fig.zip](https://github.com/OpenElements/website/files/11429066/Open.elements_design.fig.zip)

Can you please update the header.

**Comment by hendrikebbers** [comment]
fixed
