### ISSUE TITLE
Bottom of about-hendrik page is broken

### ISSUE THREAD

**Issue by hendrikebbers** [OpenElements/website#36]
In the bottom of the pace there is a large blue circle SVG (see https://open-elements-de.netlify.app/about-hendrik/). The SVG looks like it is placed 2 times since the dashed are somehow overlapping (https://open-elements-de.netlify.app/illustrations/dash-line.svg). Should I ask the designer for a new / better SVG or have we created that one?
Next to this we need a gap / padding below that SVG to not directly have the footer below the SVG.

<img width="1511" alt="Bildschirmfoto 2023-04-20 um 10 30 29" src="https://user-images.githubusercontent.com/9443847/233308172-563b924d-f7cd-40f9-bb92-cb479d5d4d15.png">

**Comment by Subtain-Farooq** [comment]
Please ask the designer to share the better SVG dash line. Every time I export dash line SVG from the Figma it is broken or distorted.

**Comment by hendrikebbers** [comment]
Designer told me that a new version is part of the sigma file: https://www.figma.com/file/uNorvr0G3GjpeUruOTOGwk/Open-elements_design?node-id=0-1

**Comment by Subtain-Farooq** [comment]
When I export the svg from the figma file, it is always distorted. Could you please ask the designer he could send the dashline SVG.

**Comment by hendrikebbers** [comment]
Can you check the new FIGMA file: https://www.figma.com/file/uNorvr0G3GjpeUruOTOGwk/Open-elements_design?type=design&node-id=0%3A1&t=4tXyvG3BoPg17v4Z-1

[Open elements_design.fig.zip](https://github.com/OpenElements/website/files/11429059/Open.elements_design.fig.zip)

**Comment by hendrikebbers** [comment]
fixed
