### ISSUE TITLE
The anchor links for the sections on the landing page should not be shown on mobile

### ISSUE THREAD

**Issue by hendrikebbers** [OpenElements/website#39]
On a mobile only the beginning of the line with the anchor links is shown. The links should be completely removed on mobile.

<img width="321" alt="Bildschirmfoto 2023-04-26 um 10 21 32" src="https://user-images.githubusercontent.com/9443847/234515172-e7431333-c953-4dae-9760-fa9ab6fa2eaf.png">

**Comment by Subtain-Farooq** [comment]
Sorry I did not understand.

**Comment by hendrikebbers** [comment]
<img width="311" alt="Bildschirmfoto 2023-05-09 um 10 46 44" src="https://user-images.githubusercontent.com/9443847/237044151-12f67fe0-a0ae-431d-a006-3d068a39fb39.png">

The marked link list should be hidden on mobile.

**Comment by hendrikebbers** [comment]
fixed
