### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by hendrikebbers** [OpenElements/website#54]
We need a 404 error page. 

Figma:https://www.figma.com/proto/uNorvr0G3GjpeUruOTOGwk/Open-elements_design?page-id=0%3A1&type=design&node-id=501-1608&viewport=-3540%2C569%2C0.13&scaling=min-zoom

<img width="1512" alt="Bildschirmfoto 2023-06-05 um 18 24 11" src="https://github.com/OpenElements/website/assets/9443847/6955c64e-d6ba-4f59-9775-9e9f70b543d5">

<img width="1512" alt="Bildschirmfoto 2023-06-05 um 18 24 14" src="https://github.com/OpenElements/website/assets/9443847/ad6a6c44-d312-40e0-a830-44eb6c796f4e">

**Comment by Subtain-Farooq** [comment]
Please share the Figma file thanks.

**Comment by hendrikebbers** [comment]
Will do. The illustration is still a placeholder and the final illustration will arrive tomorrow.

**Comment by hendrikebbers** [comment]
[figma.zip](https://github.com/OpenElements/website/files/11720589/figma.zip)

**Comment by Subtain-Farooq** [comment]
File received Thanks.

**Comment by hendrikebbers** [comment]
![404](https://github.com/OpenElements/website/assets/9443847/c66945bf-9766-4eb7-b347-2a801e267f29)
The illustration for the page
