### ISSUE TITLE
All illustration should be SVG files instead of PNGs

### ISSUE THREAD

**Issue by hendrikebbers** [OpenElements/website#7]
Currently the page contains several illustrations (+ logos) that are pixel based instead of vector based. Examples are the Open Elements Logo in the navBar and some illustrations. All that files should be changed to SVGs.

**Comment by Subtain-Farooq** [comment]
In Figma, some illustrations are in PNG, and sometimes when exporting the illustration the images get distorted. that's why some images are in PNG.

**Comment by Subtain-Farooq** [comment]
![Group 3611](https://user-images.githubusercontent.com/42765166/213397597-103938c5-c1fe-4379-a177-54900ee34433.svg)

**Comment by hendrikebbers** [comment]
Got it. I will provide all the images in SVG :)

**Comment by hendrikebbers** [comment]
![01](https://user-images.githubusercontent.com/9443847/215508446-d2850b3d-b6a7-46fc-ba70-6f4e9234a0d3.svg)
![02](https://user-images.githubusercontent.com/9443847/215508380-74a374f1-0d6c-4280-be6f-5ddc317f34fe.svg)
![03](https://user-images.githubusercontent.com/9443847/215508484-78e08b8e-837f-4879-b1af-538e124ee3fc.svg)

**Comment by hendrikebbers** [comment]
![Logo-02-transparent](https://user-images.githubusercontent.com/9443847/215509911-98626773-f008-46d9-9e81-ef72a628ff9d.svg)

**Comment by hendrikebbers** [comment]
@Subtain-Farooq files uploaded

**Comment by Subtain-Farooq** [comment]
Thanks. I will update them.

**Comment by hendrikebbers** [comment]
@Subtain-Farooq several images are still not vector based. I will upload vector based SVG files for all the images within the next days:

- [ ] OpenElements logo in header (navbar) and footer
- [ ] AdoptOpenJDK logo in about-us
- [ ] Eclipse Adoptium logo in about-us
- [ ] JakartaEE logo in about-us
- [ ] OSPO Alliance logo in about-us
- [ ] Java Community Process logo in about-us
- [ ] Wikimedia Foundation logo in about-us
- [ ] Open Source Libraries logo in about-us
- [ ] JavaLand logo in about-us
- [ ] JUG Dortmund logo in about-us
- [ ] Swirlds Labs logo in about-us
- [ ] Hedera logo in about-us
- [ ] Heise Gruppe logo in about-us

**Comment by hendrikebbers** [comment]
![Heise_online_logo](https://user-images.githubusercontent.com/9443847/227871981-1b6d60bb-34f3-497e-b485-6b3cf5e32227.svg)

**Comment by hendrikebbers** [comment]
![Jakarta_ee_logo_schooner_color_stacked_default](https://user-images.githubusercontent.com/9443847/227872115-adfb786e-7a84-4422-82a9-829b1b69f70f.svg)

**Comment by hendrikebbers** [comment]
![Wikimedia_Foundation_logo_-_vertical](https://user-images.githubusercontent.com/9443847/227872223-d932ea0a-d360-491e-81b0-4b5f8c614907.svg)

**Comment by hendrikebbers** [comment]
![hedera-hashgraph-logo-vector](https://user-images.githubusercontent.com/9443847/227872458-0f915607-d62d-4ee5-9f6e-54e4bb4cac97.svg)

**Comment by hendrikebbers** [comment]
![Opensource](https://user-images.githubusercontent.com/9443847/227872672-9c919bf5-2873-41f7-8006-b0fb409fdd93.svg)

**Comment by hendrikebbers** [comment]
![Eclipse_Adoptium_Logo](https://user-images.githubusercontent.com/9443847/227872846-a60b6e4c-7243-4ce3-b14f-42e181924736.svg)

**Comment by Subtain-Farooq** [comment]
I will replace the images with SVG
