### ISSUE TITLE
Bad layout of blog posts

### ISSUE THREAD

**Issue by hendrikebbers** [OpenElements/website#79]
I took the new layout for blog posts (see https://github.com/OpenElements/website/issues/74) and refactored it to be dynamic. 
The current PR can be found here: https://github.com/OpenElements/website/pull/70

Sadly the layout is broken since all the classes that are used in the dynamic content creation of Hugo does not fit. The current state does not have any specific layout for headlines or links for example. A concrete example can be found in the preview here: https://deploy-preview-70--open-elements.netlify.app/posts/2019-01-09-integration-docker/

This is how it looks on my machine:

<img width="1512" alt="Bildschirmfoto 2023-09-10 um 16 44 15" src="https://github.com/OpenElements/website/assets/9443847/009a8094-c6fe-41bf-a156-7809840b37ef">

**Comment by Subtain-Farooq** [comment]
The issue is fixed please check the blog branch.

![Open Elements – Integration tests with Docker](https://github.com/OpenElements/website/assets/42765166/86fee863-0b33-438b-96ec-c49fbdd3887f)
