### ISSUE TITLE
missing text style on other pages than the landing page

### ISSUE THREAD

**Issue by hendrikebbers** [OpenElements/website#9]
On pages like `/about/` or `/privacy-policy/` the text is not styled (h1/h2/h3/p/a elements all look the same). Here we need a good layout for all basic element types.

<img width="1459" alt="Bildschirmfoto 2023-01-19 um 16 56 00" src="https://user-images.githubusercontent.com/9443847/213490323-64074a91-8bd6-43c0-a63f-705860d955e8.png">

**Comment by Subtain-Farooq** [comment]
I did not find the themes folder. I need that folder to compile the css and update the css.

**Comment by hendrikebbers** [comment]
Hi @Subtain-Farooq any update with the theme? Does it works without a theme or do we need to recreate it?

**Comment by Subtain-Farooq** [comment]
Hi @hendrikebbers I have tried as shown in the blog but it's not working and I need old tailwind.config.js file

**Comment by Subtain-Farooq** [comment]
Hey, @hendrikebbers  issues are fixed please check.
